### ISSUE TITLE
Example from README issue

### ISSUE THREAD

**Issue by humanbeinc** [oleh2208/etoro-api#1]
Hi, I couldn't get the example from the README to work.

` curl -X PUT \
   http://localhost:8088/etoro-api/watchlist/byId \
   -H 'Content-Type: application/json' \
   -H 'cache-control: no-cache' \
   -d '{
 	"param": "btc"
 }'`

Server returns:
`{"timestamp":"2020-04-27T12:26:17.998+0000","status":500,"error":"Internal Server Error","message":"Asset with InstrumentID btc was not found.","path":"/etoro-api/watchlist/byId"}`

**Comment by oleh2208** [comment]
i think readme is little bit old, i will update it on the week

**Comment by dextervip** [comment]
That's nice. I am interested also. 👍

**Comment by oleh2208** [comment]
thanks for the interest to this project, i updated readme the problem was in /byId just use /byName instead

**Comment by oleh2208** [comment]
resolved
