### ISSUE TITLE
recaptcha

### ISSUE THREAD

**Issue by jfrez** [oleh2208/etoro-api#17]
im trying que docker quickstart and i got:

Session [e8b08ac0-3af3-11eb-a6c6-2f2b21a06513] - page.onError - stack:
  (anonymous function) (https://www.gstatic.com/recaptcha/releases/qc5B-qjP0QEimFYUxcpWJy5B/recaptcha__en.js:412)

after that the app crash with: "authorizationContext': Invocation of init method failed; nested exception is org.json.JSONException: JSONObject["accessToken"] not a string."

**Comment by oleh2208** [comment]
hi, it's not working with docker fornow, try to run it locally

________________________________
От: jfrez <notifications@github.com>
Отправлено: 10 декабря 2020 г. 16:31
Кому: oleh2208/etoro-api <etoro-api@noreply.github.com>
Копия: Subscribed <subscribed@noreply.github.com>
Тема: [oleh2208/etoro-api] recaptcha (#17)


im trying que docker quickstart and i got:

Session [e8b08ac0-3af3-11eb-a6c6-2f2b21a06513] - page.onError - stack:
(anonymous function) (https://www.gstatic.com/recaptcha/releases/qc5B-qjP0QEimFYUxcpWJy5B/recaptcha__en.js:412)

after that the app crash with: "authorizationContext': Invocation of init method failed;"

**Comment by jfrez** [comment]
same error runing locally, there is any method to input the captcha myself?

**Comment by jfrez** [comment]
nop, my bad, please close this, i dont want to say whats wrong :/  sorry
