### ISSUE TITLE
Support for "Paper" Account? 

### ISSUE THREAD

**Issue by JustinGuese** [oleh2208/etoro-api#2]
Hey, is it possible to somehow define Real vs Virtual Account? 
Thx in advance ;)

**Comment by oleh2208** [comment]
I'm not sure I got the question, if you asking if virtual account is supported, than answer is yes, you can use header: Mode: Demo for all requests to trade with your virtual account

**Comment by oleh2208** [comment]
you can also  see these headers in the request examples

**Comment by dextervip** [comment]
@oleh2208 Is there support to trailing stop loss? I couldn't see in the examples.

**Comment by oleh2208** [comment]
@dextervip  could you please give example what "trailing stop loss" should do?

**Comment by JustinGuese** [comment]
Thanks @oleh2208, that sounds great! I'll try to get it running ;)

**Comment by dextervip** [comment]
@oleh2208 it is enabled by checking the box in this screen. 
![Screenshot_20200506_101455](https://user-images.githubusercontent.com/964836/81181262-92d25600-8f82-11ea-94dc-3c7d819d1aa2.jpg)

**Comment by oleh2208** [comment]
i don't see this checkbox in my account

**Comment by oleh2208** [comment]
probably it requires etoro professional client which i don't have

**Comment by dextervip** [comment]
@oleh2208 I don't professional account. It is available to all accounts, It's common type of stop loss across brokers. Maybe you should check it on other types of instruments. It appears when you click on stop loss tab.

**Comment by oleh2208** [comment]
i found it now, thanks for explanation, i also added trailing sl support, you can use
it like this:
curl --location --request POST 'http://localhost:8088/etoro-api/positions/open' \
--header 'Content-Type: application/json' \
--header 'mode: ' \
--header 'Content-Type: text/plain' \
--data-raw '{
	"name": "nsdq100",
	"type": "SELL",
	"amount": 200,
	"leverage": 20,
	"tsl": true
}'

**Comment by dextervip** [comment]
Wow thank you so much! Great job!
