### ISSUE TITLE
DELETE POSITION failed with 400 Status Code

### ISSUE THREAD

**Issue by essamabas** [oleh2208/etoro-api#5]
Very Nice Job, and clean code - This is the first time, i saw Katlin code.

However, i have a Problem with Closing Position - DELETE Request:
![image](https://user-images.githubusercontent.com/10914098/82267318-38ff6200-996c-11ea-884e-faec6e6bb6d5.png)

**request:** https://www.etoro.com/sapi/trade-demo/positions/1683586719?PositionID=1683586719&client_request_id=74dbbd5f-9550-4da8-9889-88e08107ce1d

i am getting always a repsone code - 400
i tried to print the response.body() - but apparently, no body is specified.

**Comment by oleh2208** [comment]
thanks for pointing this out,
it seems they made request body required for this request, I will update my code

**Comment by oleh2208** [comment]
just made a hotfix, should work now

**Comment by essamabas** [comment]
Thanks alot, it works great
