### ISSUE TITLE
Error creating bean with name 'authorizationContext': Invocation of init method failed

### ISSUE THREAD

**Issue by roychen97** [oleh2208/etoro-api#7]
like the problem posted in another thread, but the message is different. 
I started the server with: java -jar build/libs/etoro-api-0.1.2.jar

This message was displayed before server shutdown:
`[INFO  - 2020-05-26T03:21:54.079Z] ShutdownReqHand - _handle - About to shutdown
{"missingScopes":null,"gcid":0,"realCid":0,"demoCid":0,"accessToken":null,"antiCsrfToken":null,"expirationUnixTimeMs":0,"statusCode":"BadRequest","sessionIdentifier":0,"applicationIdentifier":null,"applicationId":0,"status":400,"error":{"failureReason":"PolicyViolation_TwoFactorRequired","errorMessage":"Two Factor Verification Required","verificationId":"1de991db-454d-4b68-bf09-99dac1c4c225","maskedPhone":"**********08","maskedEmail":null,"userSocialNetworkId":null,"socialAccessToken":null,"socialNetwork":null}}`

EDIT:
it's because of my TwoFactorRequired,

**Comment by oleh2208** [comment]
Caused by 2factor auth
